#pragma once

#define ADD_ACTIVITY_CODE 1
#define SEE_ALL_ACTIVITIES_CODE 2
#define DELETE_ACTIVITY_CODE 3
#define UPDATE_ACTIVITY_CODE 4
#define FIND_ACTIVITY_CODE 5
#define FILTER_ACTIVITIES_CODE 6
#define SORT_ACTIVITIES_CODE 7

#define UNDO_CODE 8
#define ADD_TO_WISHLIST_CODE 9
#define REMOVE_ALL_FROM_WISHLIST_CODE 10
#define GENERATE_WISHLIST_CODE 11
#define EXPORT_TO_CSV_CODE 12

#define FILTER_ACTIVITIES_BY_DESCRIPTION_CODE 1
#define FILTER_ACTIVITIES_BY_TYPE_CODE 2

#define SORT_ACTIVITIES_BY_NAME_CODE 1
#define SORT_ACTIVITIES_BY_DESCRIPTION_CODE 2
#define SORT_ACTIVITIES_BY_TYPE_AND_DURATION_CODE 3